/**
 * Lista oficial de oficinas registrales de SUNARP.
 * Nombres exactos tal como los devuelve:
 * https://utilitarios-sunarp-production.apps.paas.sunarp.gob.pe/componentes/api/cboOficinasSiguelo/1
 *
 * Estos nombres son los que usa el scraper para mapear al codigoZona + codigoOficina.
 */
export const OFICINAS_SUNARP = [
  'ABANCAY',
  'ANDAHUAYLAS',
  'AREQUIPA',
  'AYACUCHO',
  'BAGUA',
  'BARRANCA',
  'CAJAMARCA',
  'CALLAO',
  'CAMANA',
  'CASMA',
  'CASTILLA _ APLAO',
  'CAÑETE',
  'CHACHAPOYAS',
  'CHEPEN',
  'CHICLAYO',
  'CHIMBOTE',
  'CHINCHA',
  'CHOTA',
  'CUSCO',
  'ESPINAR',
  'HUACHO',
  'HUAMACHUCO',
  'HUANCAVELICA',
  'HUANCAYO',
  'HUANTA',
  'HUANUCO',
  'HUARAL',
  'HUARAZ',
  'ICA',
  'ILO',
  'ISLAY _ MOLLENDO',
  'JAEN',
  'JUANJUI',
  'JULIACA',
  'LA MERCED (SELVA CENTRAL)',
  'LIMA',
  'MADRE DE DIOS',
  'MAYNAS',
  'MOQUEGUA',
  'MOYOBAMBA',
  'NAZCA',
  'OTUZCO',
  'PASCO',
  'PISCO',
  'PIURA',
  'PUCALLPA',
  'PUNO',
  'QUILLABAMBA',
  'SAN PEDRO',
  'SATIPO',
  'SICUANI',
  'SULLANA',
  'TACNA',
  'TARAPOTO',
  'TARMA',
  'TINGO MARIA',
  'TRUJILLO',
  'TUMBES',
  'YURIMAGUAS',
]
